### ISSUE TITLE
OSQP dependencies

### ISSUE THREAD

**Issue by chobby** [fdevinc/ungar#4]
Thank you for developing a great library. The description only says that Eigen and Boost.Hana are required as dependencies, do I also need to install osqp further?

**Comment by fdevinc** [comment]
Hi @chobby, thanks for reaching out! [Eigen](https://eigen.tuxfamily.org/index.php?title=Main_Page) and [Boost.Hana](https://github.com/boostorg/hana) are the only required dependencies to access the _core_ functionalities of the library: these are demonstrated in the two examples [`variable`](https://github.com/fdevinc/ungar/blob/main/example/variable.example.cpp) and [`variable_map`](https://github.com/fdevinc/ungar/blob/main/example/variable_map.example.cpp). Variables and variable maps can be integrated into any application where you need to organize all your data in a single vector.

The automatic differentiation and optimization capabilities are optional and can be enabled by setting the [CMake](http://www.cmake.org) flags  `UNGAR_ENABLE_AUTODIFF` and `UNGAR_ENABLE_OPTIMIZATION` to `ON`, respectively. For now, the latter option requires the former to be `ON`, too—you will receive informative compile errors if not. When enabled, these options will _automatically_ download the required dependencies via [CMake](http://www.cmake.org). In particular, `UNGAR_ENABLE_OPTIMIZATION` will download and make available [OSQP](https://github.com/osqp/osqp) and [osqp-cpp](https://github.com/google/osqp-cpp). So, you do not have to install anything!

If you have a local installation of [OSQP](https://github.com/osqp/osqp), then Ungar should be able to detect it by checking whether the target `osqpstatic` is defined. As a final note, autodiff and optimization are only available on Linux operating systems because they rely on an autodiff library that uses features specific to Linux.

**Comment by chobby** [comment]
Thank you very much! I will give it a try.

**Comment by fdevinc** [comment]
Great, I am always available should you have any issues!
