### ISSUE TITLE
Questions about Quadruped Example

### ISSUE THREAD

**Issue by lbt0116** [fdevinc/ungar#6]
While running the example, I noticed that when I set the contact states of all four legs to 1, indicating that they are all in contact with the ground, the calculated forces at each foot end up being the same value whatever the ref trajectroy i set.  I would appreciate a better understanding of how this example is intended to work.

**Comment by fdevinc** [comment]
Hi @lbt0116, thank you for your inquiry! It is important to note that the MPC examples in Ungar are designed to provide a high-level understanding of how optimal control problems (OCPs) can be solved over a receding horizon. The need for conciseness and a self-contained implementation means that the controller is not intended for production use.

When setting all contact states to 1 for all time steps, adjusting the `yawRateReference` to zero for feasibility, and maintaining the existing sinusoidal reference trajectory in the _z_-direction, I observed the expected ground reaction forces for tracking the robot's vertical movement. However, there is a noticeable gap between the reference body height and the measured one. This discrepancy is a result of the chosen objective function and the simplistic way reference footholds are computed.

In the objective function, the line:
```cpp
value += (r - rRef).squaredNorm();
```
assigns equal priority to tracking foothold positions (relative to the base) and base tracking. Furthermore, there is such a cost term for each foot of the robot: this easily leads to conflicts, where the robot prioritizes the former goal over the latter. It is worth noting that this behavior is expected because the example's primary purpose is to showcase library functionalities, rather than serving as a full-fledged quadrupedal locomotion MPC controller.

While there is room for improvement, the key point is that the optimizer performs its intended function. If you have further questions, feel free to ask!

**Comment by lbt0116** [comment]
Thank you very much for your answer! I will try to deploy Ungar on a physical robot.
